// **********************************************************************
// populationPercentIncrease
//
// You are given an same array of population data objects from the previous problem
// Each object represents a year going back to 1960.
// This time we are interested in the percent change in population from one year to the next.
// Return an array of sub arrays that contain each year and the population increase from the previous year.
// Note that the final year is 1960 and since we don't have data on 1959 the population increase should be null;
//
// Example :
//
// popData = [
//   { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
//     country: { id: 'US', value: 'United States' },
//     value: '325719178',
//     decimal: '0',
//     date: '2017' 
//   },
//   { 
//     indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
//     country: { id: 'US', value: 'United States' },
//     value: '323405935',
//     decimal: '0',
//     date: '2016' 
//   },
//   ...
// ]
//
// populationPercentIncrease(popData);
// => 
// [
//   ['2017', 0.7101955169492661], 
//   ['2016', 0.7316179896327505], 
//   ...
//   ['1962', 1.5262305803643226], 
//   ['1961', 1.6440653053225254], 
//   [ '1960', '' ]
// ]
//
// Hint :
// You can calculate the percent change by finding the difference between the two numbers, then dividing the result by the first number and multiplying by 100.
// **********************************************************************

var popData = [{ indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '325719178',
    decimal: '0',
    date: '2017' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '323405935',
    decimal: '0',
    date: '2016' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '321039839',
    decimal: '0',
    date: '2015' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '318622525',
    decimal: '0',
    date: '2014' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '316234505',
    decimal: '0',
    date: '2013' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '313993272',
    decimal: '0',
    date: '2012' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '311644280',
    decimal: '0',
    date: '2011' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '309338421',
    decimal: '0',
    date: '2010' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '306771529',
    decimal: '0',
    date: '2009' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '304093966',
    decimal: '0',
    date: '2008' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '301231207',
    decimal: '0',
    date: '2007' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '298379912',
    decimal: '0',
    date: '2006' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '295516599',
    decimal: '0',
    date: '2005' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '292805298',
    decimal: '0',
    date: '2004' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '290107933',
    decimal: '0',
    date: '2003' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '287625193',
    decimal: '0',
    date: '2002' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '284968955',
    decimal: '0',
    date: '2001' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '282162411',
    decimal: '0',
    date: '2000' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '279040000',
    decimal: '0',
    date: '1999' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '275854000',
    decimal: '0',
    date: '1998' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '272657000',
    decimal: '0',
    date: '1997' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '269394000',
    decimal: '0',
    date: '1996' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '266278000',
    decimal: '0',
    date: '1995' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '263126000',
    decimal: '0',
    date: '1994' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '259919000',
    decimal: '0',
    date: '1993' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '256514000',
    decimal: '0',
    date: '1992' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '252981000',
    decimal: '0',
    date: '1991' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '249623000',
    decimal: '0',
    date: '1990' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '246819000',
    decimal: '0',
    date: '1989' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '244499000',
    decimal: '0',
    date: '1988' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '242289000',
    decimal: '0',
    date: '1987' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '240133000',
    decimal: '0',
    date: '1986' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '237924000',
    decimal: '0',
    date: '1985' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '235825000',
    decimal: '0',
    date: '1984' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '233792000',
    decimal: '0',
    date: '1983' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '231664000',
    decimal: '0',
    date: '1982' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '229466000',
    decimal: '0',
    date: '1981' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '227225000',
    decimal: '0',
    date: '1980' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '225055000',
    decimal: '0',
    date: '1979' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '222585000',
    decimal: '0',
    date: '1978' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '220239000',
    decimal: '0',
    date: '1977' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '218035000',
    decimal: '0',
    date: '1976' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '215973000',
    decimal: '0',
    date: '1975' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '213854000',
    decimal: '0',
    date: '1974' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '211909000',
    decimal: '0',
    date: '1973' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '209896000',
    decimal: '0',
    date: '1972' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '207661000',
    decimal: '0',
    date: '1971' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '205052000',
    decimal: '0',
    date: '1970' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '202677000',
    decimal: '0',
    date: '1969' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '200706000',
    decimal: '0',
    date: '1968' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '198712000',
    decimal: '0',
    date: '1967' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '196560000',
    decimal: '0',
    date: '1966' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '194303000',
    decimal: '0',
    date: '1965' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '191889000',
    decimal: '0',
    date: '1964' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '189242000',
    decimal: '0',
    date: '1963' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '186538000',
    decimal: '0',
    date: '1962' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '183691000',
    decimal: '0',
    date: '1961' },
  { indicator: { id: 'SP.POP.TOTL', value: 'Population, total' },
    country: { id: 'US', value: 'United States' },
    value: '180671000',
    decimal: '0',
    date: '1960' }];

function populationPercentIncrease(data) {
  var results = [];

  for (var i = 0; i < data.length; i += 1) {
    var curYear = data[i];
    var prevYear = data[i + 1];
    var percent = null;

    if (curYear && prevYear) {
      percent = calculatePercent(curYear.value, prevYear.value);
    }

    results.push([curYear.date, percent]);
  }

  return results;
}

function calculatePercent(curYear, prevYear) { 
  var dif = Number(curYear) - Number(prevYear);
  var percent = dif / curYear;

  return percent * 100;
}


/**************DO NOT MODIFY ANYTHING UNDER THIS  LINE*****************/
module.exports = populationPercentIncrease;
